name: "Pull Request Build"

env:
  SOLUTION: 'src/CSESoftware.Repository.EntityFramework.sln'

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5

    - name: Nuget Restore for App
      run: nuget restore "${{ env.SOLUTION }}"

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build Solution
      run: msbuild "${{ env.SOLUTION }}" -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Run Unit Tests on Solution
      uses: rusty-bender/vstest-action@main
      with:
        testAssembly: '**/bin/Release/*Test*.dll'
        searchFolder: "./"
        platform: 'x64'
        ifNoFilesFound: error
        
    - name: Dependency Review
      uses:  actions/dependency-review-action@v4
      with:
        fail-on-severity: high
